"""Regenerates docs/VALIDATION.md and docs/img/*.png from a fresh backtest run.

Run with `python validate.py` after activating the venv. Takes a minute or
two since it replays both products for both the rebuilt trader and their
baselines across all three days.
"""
import os
import subprocess
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

import backtest
import baselines
import trader as traderModule

ROOT = os.path.dirname(os.path.abspath(__file__))
DOCS_DIR = os.path.join(ROOT, "docs")
IMG_DIR = os.path.join(DOCS_DIR, "img")

PEPPER = "INTARIAN_PEPPER_ROOT"
ASH = "ASH_COATED_OSMIUM"


def run_all():
    results = {}
    results[ASH] = {
        "rebuilt": backtest.run_backtest(traderModule.Trader(), ASH),
        "baseline": backtest.run_backtest(
            baselines.FixedValueMarketMaker(fairValue=10000, halfSpread=2, quoteSize=10), ASH),
    }
    results[PEPPER] = {
        "rebuilt": backtest.run_backtest(traderModule.Trader(), PEPPER),
        "baseline": backtest.run_backtest(baselines.BuyAndHoldTrader(), PEPPER),
    }
    return results


def make_hero_figure(results):
    os.makedirs(IMG_DIR, exist_ok=True)
    pepperRebuilt = results[PEPPER]["rebuilt"]
    pepperBaseline = results[PEPPER]["baseline"]

    fig, (priceAx, pnlAx) = plt.subplots(2, 1, figsize=(9, 7), sharex=True)

    priceAx.plot(pepperRebuilt["globalTs"], pepperRebuilt["mid"], linewidth=0.8)
    for day in (1, 2):
        priceAx.axvline(day * prepare_data_day_offset(), color="grey", linestyle="--", linewidth=0.8)
    priceAx.set_title("INTARIAN_PEPPER_ROOT mid price across the corrected day order")
    priceAx.set_ylabel("mid price")

    pnlAx.plot(pepperRebuilt["globalTs"], pepperRebuilt["pnl"], label="rebuilt trader (symmetric MM)")
    pnlAx.plot(pepperBaseline["globalTs"], pepperBaseline["pnl"], label="baseline (buy-and-hold to the limit)")
    pnlAx.set_title("Pepper mark-to-market PnL: rebuilt trader vs. buy-and-hold baseline")
    pnlAx.set_xlabel("global timestamp (day * 1,000,000 + intraday timestamp)")
    pnlAx.set_ylabel("pnl (XIRECS)")
    pnlAx.legend()

    fig.tight_layout()
    path = os.path.join(IMG_DIR, "pepper_price_and_pnl.png")
    fig.savefig(path, dpi=130)
    plt.close(fig)
    return path


def prepare_data_day_offset():
    import prepare_data
    return prepare_data.DAY_OFFSET


def write_validation_md(results):
    lines = []
    lines.append("# Validation")
    lines.append("")
    lines.append("Generated by `validate.py`. Do not edit by hand.")
    lines.append("")

    testResult = subprocess.run(
        [sys.executable, "-m", "pytest", "tests", "-q"],
        cwd=ROOT, capture_output=True, text=True,
    )
    lines.append("## Tests")
    lines.append("")
    lines.append("```")
    lines.append(testResult.stdout.strip().splitlines()[-1] if testResult.stdout.strip() else "(no output)")
    lines.append("```")
    lines.append("")

    lines.append("## Backtest: rebuilt trader vs. trivial baseline, all three days")
    lines.append("")
    lines.append("| product | strategy | final position | total pnl |")
    lines.append("|---|---|---:|---:|")
    for product, label in ((ASH, "ASH_COATED_OSMIUM"), (PEPPER, "INTARIAN_PEPPER_ROOT")):
        for key, name in (("rebuilt", "rebuilt trader"), ("baseline", "trivial baseline")):
            records = results[product][key]
            lines.append(f"| {label} | {name} | {records['position'].iloc[-1]} | {records['pnl'].iloc[-1]:.2f} |")
    lines.append("")

    lines.append("## Per-day pnl, rebuilt trader")
    lines.append("")
    lines.append("| product | day | pnl |")
    lines.append("|---|---:|---:|")
    for product, label in ((ASH, "ASH_COATED_OSMIUM"), (PEPPER, "INTARIAN_PEPPER_ROOT")):
        perDay = backtest.day_pnl(results[product]["rebuilt"])
        for day, pnl in perDay.items():
            lines.append(f"| {label} | {day} | {pnl:.2f} |")
    lines.append("")

    with open(os.path.join(DOCS_DIR, "VALIDATION.md"), "w") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    results = run_all()
    figPath = make_hero_figure(results)
    write_validation_md(results)
    print(f"Wrote {figPath} and docs/VALIDATION.md")


if __name__ == "__main__":
    main()
